export const CREATE_POST = 'CREATE_POST'
export const EDIT_POST = 'EDIT_POST'
export const FETCH_POSTS = 'FETCH_POSTS'
export const CREATE_COMMENT = 'CREATE_COMMENT'
export const FILL_POST = 'FILL_POST'
export const DELETE_POST = 'DELETE_POST'